### DISCUSSION TITLE
Drop the use of `.ini`  files

### DISCUSSION THREAD

**Discussion by nonunknown** [cleolibrary/CLEO-Redux#17] [Ideas]
.ini files are platform specific (windows), since things are modernizing now, like the redux and javascript support, I think .ini should be dropped, and we should use JSON or YML files which are:

* Cross-platform
* Cleaner as ini files
* Modern languages uses

Example of JSON files (already has a class built-in on Javascript and C++)

```
{
  "key1": "value1",
  "key2": "value2",
  "key3": "value3",
  "key4": 7,
  "key5": null,
  "favFriends": ["Kolade", "Nithya", "Dammy", "Jack"],
  "favPlayers": {"one": "Kante", "two": "Hazard", "three": "Didier"}
}
```

Example of YML (may require a library)
```
version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
        auth:
          username: user
          password: terter
    steps:
      - checkout
      - run: echo "this is the build job"
```
